---
- name: Install Python3 and Flask
  apt:
    name:
      - python3
      - python3-pip
      - python3-flask
      - python3-flask-socketio
      - python3-flask-sqlalchemy  
  become: true

- name: Create app directory
  file:
    path: /opt/app
    state: directory
    mode: '0755'
    owner: vagrant
    group: vagrant

- name: Copy app files
  copy:
    src: /home/vagrant/ansible/playbooks/roles/app/files/app
    dest: /opt/
    owner: vagrant
    group: vagrant

- name: Run Flask App
  command: "python3 /opt/app/app.py"
  async: 0
  poll: 0
  tags:
    - flask
