---

- name: Aktualizacja systemu
  hosts: wszystkie
  become: true
  tags:
    - update
  roles:
    - provisioning


- name: Instalacja Prometheus
  hosts: prom
  become: true
  roles:
    - prometheus
